publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [600.0, 600.0,600.0]
    pos2: [100.0, 100.0,100.0]
    pos3: [600.0, 600.0,600.0]
    pos4: [100.0, 100.0,100.0]